# Semana 2 - Código dos Slides

### imports

In [1]:
# ! pip install opencv-python
import cv2
import numpy as np

## 1. Ler e guardar imagens

## 1.1. Ler uma imagem do disco

In [2]:
# lê a imagem flower.jpg, do diretório images, e carrega-a na matriz img
img = cv2.imread("images/flower.jpg")
print(img)

[[[236 200 162]
  [236 200 162]
  [236 200 162]
  ...
  [250 225 183]
  [250 225 183]
  [252 224 183]]

 [[236 200 162]
  [236 200 162]
  [236 200 162]
  ...
  [250 225 183]
  [250 225 183]
  [252 224 183]]

 [[236 200 162]
  [236 200 162]
  [236 200 162]
  ...
  [250 225 183]
  [250 225 183]
  [252 224 183]]

 ...

 [[ 24 117  78]
  [ 23 116  77]
  [ 23 116  77]
  ...
  [ 21 125  92]
  [ 21 125  92]
  [ 21 125  92]]

 [[ 24 117  78]
  [ 24 117  78]
  [ 24 117  78]
  ...
  [ 21 125  92]
  [ 21 125  92]
  [ 21 125  92]]

 [[ 25 118  79]
  [ 25 118  79]
  [ 24 117  78]
  ...
  [ 21 125  92]
  [ 21 125  92]
  [ 21 125  92]]]


In [3]:
# lê a imagem, converte-a para tons de cinzento, e carrega-a na matriz imgGray
imgGray = cv2.imread("images/flower.jpg", cv2.IMREAD_GRAYSCALE)
print(imgGray)

[[193 193 193 ... 215 215 215]
 [193 193 193 ... 215 215 215]
 [193 193 193 ... 215 215 215]
 ...
 [ 95  94  94 ... 103 103 103]
 [ 95  95  95 ... 103 103 103]
 [ 96  96  95 ... 103 103 103]]


## 1.2. Escrever uma imagem no disco

In [4]:
# grava a imagem img no ficheiro flower.png (usa a extensão para saber o formato da imagem a escrever)
cv2.imwrite("images/flowerGrey.png",imgGray)

True

## 2. Mostrar uma imagem

In [5]:
img = cv2.imread("images/lenna.png")
# O primeiro argumento é o título da janela a criar
cv2.imshow("Imagem de teste", img)
# Espera que se carregue numa tecla antes de sair
cv2.waitKey(0)
cv2.destroyAllWindows()

> Nota – caso não se use waitKey(…), a janela aparece e desaparece quase imediatamente, porque o programa entretanto chega ao fim…

## 3. Criar imagens (ou melhor, matrizes)

> Para criar imagens novas podem-se simplesmente criar matrizes com as funções zeros(…) e ones(…) do Numpy (ou similares)

In [ ]:
height = 720
width = 1800
n = 5

# cria uma imagem img3 de width x height pixels, com 3 canais de cor, com os pixels inicializados a n
img1 = np.zeros( (height, width, 3), np.uint8 ) * (1 if n == 0 else n)

cv2.imshow("Imagem de teste", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 4. Aceder aos pixels

In [ ]:
# obter o(s) valor(es) do pixel na posição y=100, x=50
px = img[100, 50]
# escrever 0’s (preto) nas três componentes do pixel na linha 60, coluna 25
img[60, 25] = (0, 0, 0)

cv2.imshow("Imagem de teste", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 5. Atributos das matrizes Numpy

In [14]:
mg = cv2.imread("images/flower.jpg")
print(f"ndim: {img.ndim}")
print(f"shape: {img.shape}")
print(f"size: {img.size}")
print(f"dtype: {img.dtype}")
print(f"itemsize: {img.itemsize}")

ndim: 3
shape: (512, 512, 3)
size: 786432
dtype: uint8
itemsize: 1
